In [1]:
import sqlite3
import pandas as pd

connection = sqlite3.connect('day36_db.sqlite')
cursor = connection.cursor()

In [2]:
# Create table
cursor.execute('''
CREATE TABLE STOCK(
  ID INTEGER PRIMARY KEY,
  NAME TEXT NOT NULL,
  BUY INTEGER NOT NULL,
  INVESTOR TEXT NOT NULL);
''')

# Insert values
cursor.execute('''
INSERT INTO STOCK(ID,NAME,BUY,INVESTOR)
VALUES
  (1, 'ACB', 29.45, 'Nguyen'),
  (2, 'VIC', 44.55, 'Nguyen'),
  (3, 'GMD', 74.30, 'Nguyen'),
  (4, 'ACB', 28.45, 'Vinh'),
  (5, 'VIC', 40.55, 'Vinh'),
  (6, 'GMD', 60.30, 'Vinh');
''')

connection.commit()

data = pd.read_sql_query('SELECT * FROM STOCK',connection)
print(data)

   ID NAME    BUY INVESTOR
0   1  ACB  29.45   Nguyen
1   2  VIC  44.55   Nguyen
2   3  GMD  74.30   Nguyen
3   4  ACB  28.45     Vinh
4   5  VIC  40.55     Vinh
5   6  GMD  60.30     Vinh

In [3]:
# Ex 1:
query = '''
SELECT SUM(BUY) AS Tong_gia_ban
FROM STOCK;
'''

data_sum = pd.read_sql_query(query,connection)
print(data_sum)

   Tong_gia_ban
0         277.6

In [4]:
# Ex 2:
query = '''
SELECT INVESTOR, NAME, MAX(BUY) AS MAX_PRICE
FROM STOCK
GROUP BY INVESTOR;
'''

data_max_by_investor = pd.read_sql_query(query,connection)
print(data_max_by_investor)

  INVESTOR NAME  MAX_PRICE
0   Nguyen  GMD       74.3
1     Vinh  GMD       60.3